#+TITLE: Emacs Configuration
#+AUTHOR: Dileban Karunamoorthy

Emacs configuration specified in [[https://en.wikipedia.org/wiki/Literate_programming][Literate Programming]] using Emacs Org mode.

* Dependency Management
** Define Package Repositories

List of default package repositories to search from.

#+BEGIN_SRC emacs-lisp
(require 'package)

(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			 ("marmalade" . "https://marmalade-repo.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")))
#+END_SRC

** Import Package Install Utility

The function 'use-package' simplifies importing and configuring 
packages. Import packages "in-line" and configure at the same time, 
as opposed to separate these activities in two different parts of 
the file.

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
#+END_SRC
* Default Appearance
** Inhibit Startup Screen and Message

#+BEGIN_SRC emacs-lisp
  (setq inhibit-splash-screen t)
  (setq inhibit-startup-message t)
#+END_SRC

** Display Current Time

#+BEGIN_SRC emacs-lisp
  (display-time-mode t)
#+END_SRC

** Hide Tool Bar

#+BEGIN_SRC emacs-lisp
  (tool-bar-mode 0)
#+END_SRC

** Disable Scroll Bars

#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode 0)
#+END_SRC
* Backup Settings
** Disable Backups and Auto-Saves

#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+END_SRC
* Buffer Management
** Preferred Coding System

Default all new buffers to the UTF-8 coding system.
Also applies to creating new files with C-x C-f.

#+BEGIN_SRC emacs-lisp
  (prefer-coding-system 'utf-8)
#+END_SRC
** Killing Buffers

Kill current buffer without prompting for buffer name.

#+BEGIN_SRC emacs-lisp
  (defun kill-current-buffer ()
    "Kills the current buffer."
    (interactive)
    (kill-buffer (current-buffer)))
  (global-set-key (kbd "C-x k") 'kill-current-buffer)
#+END_SRC

** Enable 'ibuffers' as Default

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ibuffer)
#+END_SRC
* Basic Editing
** Highlight Current Line

Highlights current line when using the windowing system. 
Not enabled for command line.

#+BEGIN_SRC emacs-lisp
  (when window-system (add-hook 'prog-mode-hook 'hl-line-mode))
#+END_SRC
