#+TITLE: Emacs Configuration
#+AUTHOR: Dileban Karunamoorthy

Emacs configuration specified in [[https://en.wikipedia.org/wiki/Literate_programming][Literate Programming]] using Emacs Org mode.

* Dependency Management
** Define Package Repositories

List of default package repositories to search from.

#+BEGIN_SRC emacs-lisp
(require 'package)

(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			 ("marmalade" . "https://marmalade-repo.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")))
#+END_SRC

** Import Package Install Utility

The function 'use-package' simplifies importing and configuring 
packages. Import packages "in-line" and configure at the same time, 
as opposed to separate these activities in two different parts of 
the file.

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
#+END_SRC
** Try Package Before Installing

Utility for trying packages before installing.

#+BEGIN_SRC emacs-lisp
(use-package try
	:ensure t)
#+END_SRC
** Customizations

Save all custom-settings to a separate file

#+BEGIN_SRC emacs-lisp
(setq custom-file "~/.emacs.d/custom-settings.el")
(load custom-file t)
#+END_SRC
* Environment
** Using Environment Variables 

Load system dependent variables from env.el. 

#+BEGIN_SRC emacs-lisp
(defvar env-file "~/.emacs.d/env.el")
(when (file-exists-p env-file)
  (load-file env-file))
#+END_SRC
* Default Appearance
** Inhibit Startup Screen and Message

#+BEGIN_SRC emacs-lisp
(setq inhibit-splash-screen t)
(setq inhibit-startup-message t)
#+END_SRC
** Yes/No to Y/N

#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Display Current Time
	
#+BEGIN_SRC emacs-lisp
(display-time-mode t)
#+END_SRC
** Tab Width

#+BEGIN_SRC emacs-lisp
(setq-default tab-width 3)
#+END_SRC
** Hide Tool Bar

#+BEGIN_SRC emacs-lisp
(tool-bar-mode 0)
#+END_SRC
** Hide Menu Bar

#+BEGIN_SRC emacs-lisp
(menu-bar-mode 0)
#+END_SRC

** Disable Scroll Bars

#+BEGIN_SRC emacs-lisp
(scroll-bar-mode 0)
#+END_SRC
** Theme

See [[https://emacsthemes.com/][Emacs Themes]] for a collection of themes.

#+BEGIN_SRC emacs-lisp
		;; (use-package solarized-theme
		;;   :ensure t
		;;   :config
		;;   (load-theme 'solarized-dark)
		;; )

(use-package dracula-theme
 	:ensure t)

#+END_SRC
** Dashboard

[[https://github.com/rakanalh/emacs-dashboard][Emacs Dashboard]] provides a startup screen with important locations.

#+BEGIN_SRC emacs-lisp
(use-package dashboard
  :ensure t
  :config
  (dashboard-setup-startup-hook)
  (setq dashboard-items '(
        (recents  . 5)
        (bookmarks . 5)
		  (projects . 5)))
)
#+END_SRC
** Save/Restore Desktop 

#+BEGIN_SRC emacs-lisp
(desktop-save-mode 1)
#+END_SRC

* Key Management
** Assitance for key completions

[[https://github.com/justbur/emacs-which-key][which-key]] displays possible key-bindings for partially completed
commands.

#+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :config
    (which-key-mode))
#+END_SRC
* Backup Settings
** Disable Backups and Auto-Saves

#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)
(setq auto-save-default nil)
#+END_SRC
* File and Buffer Management
** Dired

#+BEGIN_SRC emacs-lisp
(setq dired-listing-switches "-al")
(global-set-key (kbd "C-c j") 'dired-jump)

(use-package dired
:bind (:map dired-mode-map
         ("u" . dired-up-directory)
         ("i" . dired-previous-line)
         ("k" . dired-next-line))
)
#+END_SRC
** Preferred Coding System

Default all new buffers to the UTF-8 coding system.
Also applies to creating new files with C-x C-f.

#+BEGIN_SRC emacs-lisp
(prefer-coding-system 'utf-8)
#+END_SRC
** Killing Buffers

Kill current buffer without prompting for buffer name.

#+BEGIN_SRC emacs-lisp
(defun kill-current-buffer ()
  "Kills the current buffer."
  (interactive)
  (kill-buffer (current-buffer)))
(global-set-key (kbd "C-x k") 'kill-current-buffer)
#+END_SRC

** Enable 'ibuffers' by Default

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+END_SRC
** Recent Files

Enables quick access to recent (previous/past) files.

#+BEGIN_SRC emacs-lisp
(recentf-mode 1)
(global-set-key (kbd "C-x p") 'helm-recentf)
#+END_SRC
** Auto Insert 

Default auto-insert settings when creating new buffers

#+BEGIN_SRC emacs-lisp
(auto-insert-mode)
;;  Trailing slash important
(setq auto-insert-directory "~/.emacs.d/templates/")
;; Disable prompt before insertion
(setq auto-insert-query nil)
#+END_SRC
* Basic Editing
** Highlight Current Line

Highlights current line when using the windowing system. 
Not enabled for command line.

#+BEGIN_SRC emacs-lisp
(when window-system (add-hook 'prog-mode-hook 'hl-line-mode))
#+END_SRC
** Text Scrolling

Scroll text in current window one line at a time.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-0") (lambda ()(interactive)(scroll-down 1)))
(global-set-key (kbd "C-9") (lambda ()(interactive)(scroll-up 1)))
#+END_SRC
** Multiple Cursors

[[https://github.com/magnars/multiple-cursors.el][Multiple cursors]] for uber text manipulation. Also see [[https://github.com/jwiegley/dot-emacs/blob/master/init.el][John Wiegley]]'s
configuration for interesting workflows.

#+BEGIN_SRC emacs-lisp
(use-package multiple-cursors
  :ensure t
  :bind
  ("C-S-c C-S-c" . 'mc/edit-lines)
  ("C->" . 'mc/mark-next-like-this)
  ("C-<" . 'mc/mark-previous-like-this)
  ("C-c C-<" . 'mc/mark-all-like-this)
)
#+END_SRC

** Moving Point Quickly Within Screen Area

Moves point quickly within the visible screen area.

#+BEGIN_SRC emacs-lisp
(use-package avy
   :ensure t
   :bind ("M-s" . avy-goto-char))
#+END_SRC
** Finding Stuff

Finding stuff includes searching text within buffers, as well as
finding buffers, files, and commonly used commands.

[[https://github.com/abo-abo/swiper][Swiper]] is a replacement for the default search, which shows a
convenient overview of all matches. 

#+BEGIN_SRC emacs-lisp
;; Commented out. Prefer using Helm Swoop instead.
;; (use-package swiper
;;  :ensure t
;;  :bind ("C-s" . swiper)
;;  :config)
#+END_SRC

[[https://github.com/ShingoFukuyama/helm-swoop][Helm Swoop]] is a replacement for the default search, which shows a 
convenient overview of all matches.

#+BEGIN_SRC emacs-lisp
(use-package helm-swoop
  :ensure t
  :bind ("C-s" . helm-swoop-without-pre-input)
  :config
  (define-key helm-swoop-map (kbd "C-r") 'helm-previous-line)
  (define-key helm-swoop-map (kbd "C-s") 'helm-next-line)
  (define-key helm-multi-swoop-map (kbd "C-r") 'helm-previous-line)
  (define-key helm-multi-swoop-map (kbd "C-s") 'helm-next-line)
  (setq helm-swoop-use-line-number-face t)
  (set-face-attribute 'helm-swoop-target-word-face nil 
      :weight 'bold
      :foreground "deep pink")
)
#+END_SRC

Ivy is a generic completion system for Emacs, while Counsel builds 
on Ivy to add completions to a number of commonly used emacs commands.
This enhances searchability of buffers, files, commands, functions, 
variables, etc.

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :ensure t
  :config
  (ivy-mode 1))

(use-package counsel
  :ensure t
  :bind 
  (("M-y" . counsel-yank-pop)
    :map ivy-minibuffer-map
    ("M-y" . ivy-next-line)))
#+END_SRC

Override default bindings added by Counsel with Helm for M-x, finding
files, buffers, and bookmarks.

#+BEGIN_SRC emacs-lisp
(use-package helm
  :ensure t
  :bind 
  ("M-x" . helm-M-x)
  ("C-x C-f" . helm-find-files)
  ("C-x C-b" . helm-buffers-list)
  ("C-x b" . helm-buffers-list)
  ("C-x r b" . helm-bookmarks)
  :config
  (setq helm-autoresize-max-height 30
        helm-autoresize-min-height 30)
  (helm-autoresize-mode 1)
  (set-face-attribute 'helm-selection nil 
      :background "violet red"
      :foreground "white")
)
#+END_SRC
** Expand Region and Replace

Expand region and replace

#+BEGIN_SRC emacs-lisp
(use-package expand-region
  :ensure t
  :bind
  ("C-`" . er/expand-region)
  :config
  (pending-delete-mode t)
)
#+END_SRC
** Unfil Region

The reverse of fill-region. Useful when copying text from emacs to
other destinations.

#+BEGIN_SRC emacs-lisp
(use-package unfill
  :ensure t)
#+END_SRC
** Spell Checker

See [[https://lists.gnu.org/archive/html/help-gnu-emacs/2014-04/msg00030.html][here]] for instructions on setting up hunspell

#+BEGIN_SRC emacs-lisp
(setq ispell-program-name (locate-file "hunspell"
                exec-path exec-suffixes 'file-executable-p))
#+END_SRC
** Crux 

[[https://github.com/bbatsov/crux][Crux]] provides an number of useful productivity features. The followig
are being used here:

+ Smarter move to begining of line
+ Smarter opening of new line
+ Killing lines backwards

#+BEGIN_SRC emacs-lisp
(use-package crux
  :ensure t
  :bind 
    ("M-o" . crux-smart-open-line-above)
    ("C-<backspace>" . crux-kill-line-backwards)
	 ([remap move-beginning-of-line] . crux-move-beginning-of-line)
)

#+END_SRC

# Insert line above point and moves point above with proper
# indentation. Primarily intended for use while coding. Source: [[https://www.emacswiki.org/emacs/OpenNextLine][Emacs
# Wiki]].

# #+BEGIN_SRC emacs-lisp
#   (defun open-previous-line (arg)
# 	  "Open a new line before the current one. 
# 	  See also `newline-and-indent'."
# 	  (interactive "p")
# 	  (beginning-of-line)
# 	  (open-line arg)
# 	  (when newline-and-indent
# 	  (indent-according-to-mode)))

#   (global-set-key (kbd "M-o") 'open-previous-line)
#   (defvar newline-and-indent t)
# #+END_SRC

** Highlight indentation

Enables visual cues for indentation

#+BEGIN_SRC emacs-lisp
(use-package highlight-indent-guides
  :ensure t
  :config
  (setq highlight-indent-guides-method 'character)
)
#+END_SRC
* Typesetting Systems
** Document Preparation with LaTex

Using AUCTeX for producing TeX based content, including LaTex,
requires a TeX system such as TeX Live. To acquire TeX Live for
Windows, download the installer from [[https://www.tug.org/texlive/acquire-netinstall.html][here]]. On Ubuntu, install
(texlive-full) from repositories.

Helpful links:

- [[https://tex.stackexchange.com/questions/50827/a-simpletons-guide-to-tex-workflow-with-emacs][A Simpleton Guide to TeX Workflow with Emacs]]
 

#+BEGIN_SRC emacs-lisp
(use-package auctex
  :ensure t
  :mode ("\\.tex\\'" . TeX-latex-mode)
)
#+END_SRC
** Org Mode

Styling orgmode, inspired by [[https://thraxys.wordpress.com/2016/01/14/pimp-up-your-org-agenda/][this]]. For a list of symbols see [[https://www.w3schools.com/charsets/ref_html_entities_4.asp][here]].

#+BEGIN_SRC emacs-lisp
(use-package org-bullets
  :ensure t
  :init
  (setq org-bullets-bullet-list
      '("◉" "●" "○" "▪" "▪"))
  :config
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
  (setq org-ellipsis " ▾")
)
#+END_SRC

Insert default header when creating new files

#+BEGIN_SRC emacs-lisp
(define-auto-insert "\.org" "default.org")
#+END_SRC
** Markdown Mode

Setup major mode for [[https://jblevins.org/projects/markdown-mode/][Markdown]].

#+BEGIN_SRC emacs-lisp
(use-package markdown-mode
  :ensure t
  :commands (markdown-mode gfm-mode)
  :mode (("README\\.md\\'" . gfm-mode))
  :init (setq markdown-command (getenv "MDCMD"))
)
#+END_SRC
* Programming
** General

[[https://github.com/flycheck/flycheck][Flycheck]] is a syntax checking extension that supports over 50 
languages.

#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))
#+END_SRC

[[https://github.com/joaotavora/yasnippet][yasnippet]] template system for convenient expansions.
#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :ensure t
  :config
  (yas-global-mode t))
#+END_SRC

[[https://github.com/auto-complete/auto-complete][auto-complete]] enables auto-completion feature for various modes
in Emacs. 

# #+BEGIN_SRC emacs-lisp
# (use-package auto-complete
#   :ensure t
#   :init
#   :config
#   (setq ac-ignore-case nil)
#   (progn 
#      (ac-config-default))
# )
# #+END_SRC

[[https://company-mode.github.io/][company-mode]] for text completion in emacs.

#+BEGIN_SRC emacs-lisp
(use-package company
  :ensure t
  :config
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 3)
  (global-company-mode t)
)
#+END_SRC

Show matching parentheses.

#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)
#+END_SRC

** Working with Projects

[[https://github.com/bbatsov/projectile][Projectile]], a useful project interaction extension that makes working
with projects (e.g. any directory with .git) easy. 

#+BEGIN_SRC emacs-lisp
(use-package projectile
  :ensure t
  :init
    (projectile-mode 1)
  :config
  (setq projectile-completion-system 'helm)
  (define-key projectile-mode-map (kbd "M-p") 'projectile-command-map))
#+END_SRC

[[https://github.com/bbatsov/helm-projectile][helm-projectile]] is helm mode for projectile. 

#+BEGIN_SRC emacs-lisp
(use-package helm-projectile
  :ensure t
  :init
  (helm-projectile-on))
#+END_SRC
** Magit

[[https://magit.vc/][Magit]] is a Git porcelain for Emacs.

#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :config 
  (setq magit-push-always-verify nil)
)
#+END_SRC
** Docker

#+BEGIN_SRC emacs-lisp
(use-package dockerfile-mode
  :ensure t)
#+END_SRC

** Protocol Buffers

#+BEGIN_SRC emacs-lisp
(use-package protobuf-mode
  :ensure t)
#+END_SRC
** Solidity

#+BEGIN_SRC emacs-lisp
(use-package solidity-mode
  :ensure t)
#+END_SRC
** Golang

Setup [[https://github.com/dominikh/go-mode.el][go-mode]] for editing Go code. In order to use go-mode effectively
install the following tools and ensure they are availalbe in the PATH:

+ [[https://godoc.org/golang.org/x/tools/cmd/goimports][goimports]]: =go get golang.org/x/tools/cmd/goimports=
+ [[https://github.com/rogpeppe/godef][godef]]: =go get github.com/rogpeppe/godef=
+ [[https://github.com/golang/lint][golint]]: =go get -u golang.org/x/lint/golint=
+ [[https://github.com/kisielk/errcheck][errcheck]]: =go get -u github.com/kisielk/errcheck=
+ [[https://godoc.org/golang.org/x/tools/cmd/guru][guru]]: =go get golang.org/x/tools/cmd/guru=

NOTE: Go imports relies on existence of the GNU `diff` util in PATH.

#+BEGIN_SRC emacs-lisp
(use-package go-mode
  :ensure t
  :bind
  :config
  (add-hook 'go-mode-hook
          (lambda () 
			 (define-key go-mode-map (kbd "M-.") 'godef-jump)
			 (setq gofmt-command "goimports")
			 (add-hook 'before-save-hook 'gofmt-before-save)))
)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package go-guru
  :ensure t)
#+END_SRC

To get auto complete working, install [[https://github.com/nsf/gocode][gocode]] along with 
[[https://github.com/auto-complete/auto-complete][auto-complete]] (see above) and [[https://github.com/nsf/gocode/tree/master/emacs][go-autocomplete]].

#+BEGIN_SRC emacs-lisp
(use-package go-autocomplete
  :ensure t)
#+END_SRC
** Haskell

+ [[https://github.com/serras/emacs-haskell-tutorial/blob/master/tutorial.md][Haskell for Emacs]] - Useful instructions for setting up Haskell for Emacs.

#+BEGIN_SRC emacs-lisp
(use-package haskell-mode
  :ensure t)
(add-hook 'haskell-mode-hook #'interactive-haskell-mode)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package hindent
  :ensure t)
(add-hook 'haskell-mode-hook #'hindent-mode)
#+END_SRC
** Racket

Setup [[https://github.com/greghendershott/racket-mode][major mode]] for [[https://racket-lang.org/][Racket]] source files and Racket REPL.

#+BEGIN_SRC emacs-lisp
(use-package racket-mode
  :ensure t)
#+END_SRC
** Rust

Setup major mode for programming with Rust

# #+BEGIN_SRC emacs-lisp
# (use-package rustic)
# #+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package rust-mode
  :ensure t
  :config
  (setq rust-format-on-save t)
  (add-hook 'rust-mode-hook
          (lambda () 
			 (setq indent-tabs-mode nil)
			 (define-key rust-mode-map (kbd "C-c C-c") 'rust-run)))
)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package lsp-mode
  :hook(
  (rust-mode . lsp)
  (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package cargo
  :ensure t
  :config
  (add-hook 'rust-mode-hook 'cargo-minor-mode)
)
#+END_SRC
** Yaml

Setup [[https://github.com/yoshiki/yaml-mode][major mode]] for editing YAML files.

#+BEGIN_SRC emacs-lisp
(use-package yaml-mode
  :ensure t
  :config 
  (add-hook 'yaml-mode-hook
      '(lambda ()
         (define-key yaml-mode-map "\C-m" 'newline-and-indent)
			(setq highlight-indent-guides-mode t)
)))
#+END_SRC
* References

List of emacs configurations for inspiration

+ [[https://github.com/hrs/dotfiles/tree/master/emacs/.emacs.d][HRS]]
+ [[https://github.com/zamansky/using-emacs/blob/master/myinit.org][Mike Zamansky]]
+ [[https://github.com/daedreth/UncleDavesEmacs][Dawid Eckert (Uncle Dave)]]
+ [[https://github.com/munen/emacs.d][Alain M. Lafon (Munen)]]
+ [[https://github.com/bbatsov/emacs.d/blob/master/init.el][Bozhidar Batsov]]
+ [[https://github.com/jwiegley/dot-emacs/blob/master/init.el][John Wiegley]]
+ [[https://github.com/abo-abo/oremacs][Oleh Krehel (abo abo)]]
